/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Library {

    public static void main(String[] args) {
        int[] num = roll(7);
        for(int rolls : num){
            System.out.println(rolls);
        }
        int[] testArr = {1 ,4 , 5 , 4 , 2};
        System.out.println(containsDuplicates(testArr));

        int[] testAvg = { 4 , 7 , 2 , 7};
        System.out.println(calculatingAverages(testAvg));

        printLowesAvgTem();

        analyzingWeatherData();

        tallyingElection();
    }

    public boolean someLibraryMethod() {
        return true;
    }

    public static void printLowesAvgTem() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int lowestIndex = findLowestAverageIndex(weeklyMonthTemperatures);
        int[] lowestAverageArray = weeklyMonthTemperatures[lowestIndex];

        System.out.println("Array with the lowest average temperature:");
        for (int temperature : lowestAverageArray) {
            System.out.print(temperature + " ");
        }
    }

    public static int[] roll(int n){
        int[] dice = new int[n];
        Random random = new Random();
        for(int i = 0 ; i < dice.length ; i++){
            dice[i] = random.nextInt(7);
        }
        return dice;
    }

    public static boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length - 1; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static int calculatingAverages(int[] arr){
        int sum = 0;
        for (int i = 0; i < arr.length ; i++) {
            sum += arr[i];
        }
        return sum / arr.length;
    }

    public static int findLowestAverageIndex(int[][] arrays) {
        int lowestIndex = 0;
        double lowestAverage = calculateAverage(arrays[0]);

        for (int i = 1; i < arrays.length; i++) {
            double average = calculateAverage(arrays[i]);
            if (average < lowestAverage) {
                lowestAverage = average;
                lowestIndex = i;
            }
        }

        return lowestIndex;
    }

    public static double calculateAverage(int[] array) {
        int sum = 0;
        for (int num : array) {
            sum += num;
        }
        return (double) sum / array.length;
    }

    public static void analyzingWeatherData() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        Set<Integer> temp = new HashSet<>();
        List<Integer> list = new ArrayList<>();

        // fill hash set from array to be unique
        for (int[] numArr : weeklyMonthTemperatures) {
            for (int i = 0; i < numArr.length; i++) {
                temp.add(numArr[i]);
            }
        }

        // remove duplicate
        list.addAll(temp);
        // sort list
        Collections.sort(list);

        int maxTemp = Collections.max(list);
        int minTemp = Collections.min(list);

        System.out.println("High: " + maxTemp);
        System.out.println("Low: " + minTemp);
        getMissingNum(list, minTemp, maxTemp).forEach(integer ->
                System.out.println("Never saw temperature: " + integer));
    }

    public static List<Integer> getMissingNum(List<Integer> arrList, int minNum, int maxNum) {
        List<Integer> newList = new ArrayList<>();

        for (int i = minNum; i <= maxNum; i++) {
            if (!arrList.contains(i)) {
                newList.add(i);
            }
        }
        return newList;
    }

    public static void tallyingElection() {
        //second task
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        Collections.sort(votes);
        System.out.println(tally(votes));
    }

    public static String tally(List<String> votesList) {
        // remove duplicate items
        Set<String> winners = new HashSet<>(votesList);
        Map<String, Integer> winnerMap = new HashMap<>();

        // loop through winners set . and put it in Map<String , Integer>
        for (String names : winners) {
            winnerMap.put(names, Collections.frequency(votesList, names));
        }

        // iteration over Map to get the winner that most repeated .
        String key = "";
        for (Map.Entry<String, Integer> entry : winnerMap.entrySet()) {
            if (entry.getValue().equals(Collections.max(winnerMap.values()))) {
                key = entry.getKey();
            }
        }

        return key;
    }
}
