/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

public class App {

    public static void main(String[] args) {

        // file I/O Starting
        try{
            checkForMissingSemicolons("resources/gates.js").stream().forEach(s -> System.out.println(s));
        }catch (IOException ex){
            ex.printStackTrace();
        }
    }

    public static List<String> checkForMissingSemicolons(String filePath) throws IOException{
        List<String> errorMessages = new ArrayList<>();
        BufferedReader reader = new BufferedReader(new FileReader(filePath));
        try {
            String line;
            int lineNumber = 1;

            while ((line = reader.readLine()) != null) {
                if (!shouldSkipLine(line)) {
                    if (!line.trim().isEmpty() && !line.trim().endsWith(";")) {
                        errorMessages.add("Line " + lineNumber + ": Missing semicolon.");
                    }
                }
                lineNumber++;
            }
        } catch (IOException e) {
            reader.close();
            e.printStackTrace();
        }
        reader.close();
        return errorMessages;
    }

    public static boolean shouldSkipLine(String line) {
        line = line.trim();
        return line.isEmpty() || line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else");
    }
}

