/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Path;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testFileNoError() throws IOException {
        List<String> errors = App.checkForMissingSemicolons("./resources/gatesTest1.js");
        List<String> expectedError = new ArrayList<>();
        assertEquals(expectedError.size(),errors.size());
    }

    @Test
    void testFileOneError() throws IOException {
        List<String> errors = App.checkForMissingSemicolons("./resources/gatesTest2.js");
        List<String> expectedError = new ArrayList<>();
        expectedError.add("Line 5");

        assertEquals(expectedError.size(),errors.size());
    }

    @Test
    void testFileTwoError() throws IOException {
        List<String> errors = App.checkForMissingSemicolons("./resources/gatesTest3.js");
        List<String> expectedError = new ArrayList<>();
        expectedError.add("Line 3");
        expectedError.add("Line 5");

        assertEquals(expectedError.size(),errors.size());
    }

    @Test
    void testFileManyError() throws IOException {
        List<String> errors = App.checkForMissingSemicolons("./resources/gatesTest4.js");
        List<String> expectedError = new ArrayList<>();

        assertEquals(expectedError.size(),errors.size());
    }
}
